name: NMLQuivers
version: '1.0'
main: io.github.NoOne.nMLQuivers.NMLQuivers
api-version: '1.21'
depends:
  - NMLPlayerStats
  - NMLItems
commands:
  generateQuiver:
    description: Generates a quiver for the player
    usage: /<command>